"""Generate the bundled M350-50A B-H table from the open Modelica model.

The source model is Modelica Standard Library's BSD-3-Clause-licensed
``M350_50A`` record and ``mu_rApprox`` function.  Keeping the parameters and
formula here makes the distributed CSV reproducible and reviewable.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

MU_0 = 4.0 * math.pi * 1e-7
MU_I = 1210.0
B_MY_MAX_T = 1.16
C_A = 24630.0
C_B = 2.44
N = 14.0

SOURCE_MODEL = (
    "https://github.com/modelica/ModelicaStandardLibrary/blob/master/"
    "Modelica/Magnetic/FluxTubes/Material/SoftMagnetic/ElectricSheet/M350_50A.mo"
)
SOURCE_FUNCTION = (
    "https://github.com/modelica/ModelicaStandardLibrary/blob/master/"
    "Modelica/Magnetic/FluxTubes/Material/SoftMagnetic/mu_rApprox.mo"
)
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "materials"
    / "electrical-steel"
    / "M350-50A.csv"
)


def relative_permeability(b_t: float) -> float:
    """Return the Modelica approximation of relative permeability at ``B``."""

    normalized_b = abs(b_t / B_MY_MAX_T)
    return 1.0 + (MU_I - 1.0 + C_A * normalized_b) / (
        1.0 + C_B * normalized_b + normalized_b**N
    )


def magnetic_field_strength(b_t: float) -> float:
    """Convert the approximated relative permeability into H [A/m]."""

    if b_t == 0.0:
        return 0.0
    return b_t / (MU_0 * relative_permeability(b_t))


def sample_flux_densities() -> list[float]:
    """Sample the fit densely through its knee and hard-saturation region."""

    return [0.0, 0.000001, *(index / 100.0 for index in range(1, 251))]


def render_csv() -> str:
    """Render the deterministic solver table and its provenance preamble."""

    lines = [
        "# Generated by tools/generate_m350_50a_bh.py; do not edit by hand.",
        "# Material: M350-50A (1.0810) @ 50 Hz; sample: sheet strip; measurement: Epstein frame.",
        f"# Source model: {SOURCE_MODEL}",
        f"# Source formula: {SOURCE_FUNCTION}",
        "# Source license: BSD-3-Clause; retained notice is in THIRD_PARTY_NOTICES.md.",
        "# Model parameters: mu_i=1210, B_myMax=1.16 T, c_a=24630, c_b=2.44, n=14.",
        "# mu_r(B) = 1 + (mu_i - 1 + c_a*|B/B_myMax|) / (1 + c_b*|B/B_myMax| + |B/B_myMax|^n).",
        "# H(B) = B / (mu_0 * mu_r(B)).",
        "B_T,H_A_per_m",
    ]
    lines.extend(
        f"{b_t:.6f},{magnetic_field_strength(b_t):.9f}"
        for b_t in sample_flux_densities()
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in table is not the deterministic generator output",
    )
    args = parser.parse_args()

    output = args.output.resolve()
    rendered = render_csv()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"generated M350-50A table is stale: {output}")
        print(f"verified {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
